"user strict"; //treat all code as newer version

//alert("mc") //we are using node js, not browser

console.log(2+3); console.log("kumar")//code readablility should be organiged

//ecma sript is the original documents of js. and   mdm

let name ="kowshik"
let age=55
let isLoggedIn=false

//number=> 2 power to 53(range)
//bigint
//string=>""
//boolean=>true/false
//null=>standalone value
//undefined=>
//symbol--use in react (use for uniqueness)
//object

console.log(typeof "kowshik")
console.log(typeof age);
console.log(typeof null) // it show that null is a object
console.log(typeof undefined) // it show object