// use ctrl + space bar to active any type of suggestion  from vs code


// console.log("KOWSHIK")
const accountId="242-16-076"
let accountEmial="kowsjik87@gmial.com"
var accountPassword="897"

// we can use without write something before it
accountCity="gazipur"


 let accountState;

//accountId=456 // not allowed

// these 3 are allowed cause there are no constant values.
accountEmial="kloloik87@gmial.com"
 accountPassword="00897"
accountCity="gaznnipur"


console.log(accountId);
/*
{} called scope
prefer not to use var
cause of issue in block scope and functional scope

*/
console.table([accountId,accountEmial,accountPassword,accountCity,accountState])